import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const keys = () =>
  createEnv({
    client: {
      NEXT_PUBLIC_ANALYTICS_LOCALHOST: z.string().optional(),
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_API_KEY: z.string().optional(),
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_AUTO_TRACK_PAGE_VIEWS: z
        .string()
        .optional(),
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_AUTO_TRACK_ERRORS: z.string().optional(),
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_TRACK_VITALS: z.string().optional(),
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_RESPECT_DO_NOT_TRACK: z
        .string()
        .optional(),
      NEXT_PUBLIC_ANALYTICS_GA_MEASUREMENT_ID: z.string().optional(),
      NEXT_PUBLIC_ANALYTICS_GA_DISABLE_PAGE_VIEWS_TRACKING: z
        .string()
        .optional(),
      NEXT_PUBLIC_ANALYTICS_POSTHOG_KEY: z.string().optional(),
      NEXT_PUBLIC_ANALYTICS_POSTHOG_HOST: z.string().url().optional(),
      NEXT_PUBLIC_ANALYTICS_UMAMI_HOST: z.string().url().optional(),
      NEXT_PUBLIC_ANALYTICS_UMAMI_WEBSITE_ID: z.string().optional(),
    },
    runtimeEnv: {
      NEXT_PUBLIC_ANALYTICS_LOCALHOST:
        process.env.NEXT_PUBLIC_ANALYTICS_LOCALHOST,
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_API_KEY:
        process.env.NEXT_PUBLIC_ANALYTICS_HIMETRICA_API_KEY,
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_AUTO_TRACK_PAGE_VIEWS:
        process.env.NEXT_PUBLIC_ANALYTICS_HIMETRICA_AUTO_TRACK_PAGE_VIEWS,
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_AUTO_TRACK_ERRORS:
        process.env.NEXT_PUBLIC_ANALYTICS_HIMETRICA_AUTO_TRACK_ERRORS,
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_TRACK_VITALS:
        process.env.NEXT_PUBLIC_ANALYTICS_HIMETRICA_TRACK_VITALS,
      NEXT_PUBLIC_ANALYTICS_HIMETRICA_RESPECT_DO_NOT_TRACK:
        process.env.NEXT_PUBLIC_ANALYTICS_HIMETRICA_RESPECT_DO_NOT_TRACK,
      NEXT_PUBLIC_ANALYTICS_GA_MEASUREMENT_ID:
        process.env.NEXT_PUBLIC_ANALYTICS_GA_MEASUREMENT_ID,
      NEXT_PUBLIC_ANALYTICS_GA_DISABLE_PAGE_VIEWS_TRACKING:
        process.env.NEXT_PUBLIC_ANALYTICS_GA_DISABLE_PAGE_VIEWS_TRACKING,
      NEXT_PUBLIC_ANALYTICS_POSTHOG_KEY:
        process.env.NEXT_PUBLIC_ANALYTICS_POSTHOG_KEY,
      NEXT_PUBLIC_ANALYTICS_POSTHOG_HOST:
        process.env.NEXT_PUBLIC_ANALYTICS_POSTHOG_HOST,
      NEXT_PUBLIC_ANALYTICS_UMAMI_HOST:
        process.env.NEXT_PUBLIC_ANALYTICS_UMAMI_HOST,
      NEXT_PUBLIC_ANALYTICS_UMAMI_WEBSITE_ID:
        process.env.NEXT_PUBLIC_ANALYTICS_UMAMI_WEBSITE_ID,
    },
    emptyStringAsUndefined: true,
  });
